/**
 * Cloudflare Worker entry point: wraps the OpenNext-generated worker to add a
 * `scheduled` handler, because Cloudflare Cron Triggers invoke the worker
 * directly instead of calling an HTTP path.
 *
 * Each cron expression here must also be listed under `triggers.crons` in
 * wrangler.jsonc.
 */

// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from './.open-next/worker.js';

type Env = { CRON_SECRET?: string } & Record<string, unknown>;
type ExecutionContext = { waitUntil(promise: Promise<unknown>): void };

const CRON_ROUTES: Record<string, string[]> = {
    // Daily at 05:00 UTC: reminders, birthday coupons, dunning, cart cleanup, maintenance alerts.
    '0 5 * * *': ['/api/cron/daily-unified', '/api/cron/maintenance-check'],
};

async function runCronRoute(path: string, env: Env, ctx: ExecutionContext) {
    // The host is irrelevant: the request is handed straight to the Next handler.
    const request = new Request(`https://cron.internal${path}`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${env.CRON_SECRET ?? ''}` },
    });
    const response: Response = await handler.fetch(request, env, ctx);
    const body = await response.text();
    if (!response.ok) {
        throw new Error(`[cron] ${path} failed with ${response.status}: ${body.slice(0, 500)}`);
    }
    console.log(`[cron] ${path} ok: ${body.slice(0, 500)}`);
}

export default {
    fetch: handler.fetch,

    async scheduled(controller: { cron: string }, env: Env, ctx: ExecutionContext) {
        const paths = CRON_ROUTES[controller.cron];
        if (!paths) {
            console.warn(`[cron] No routes configured for "${controller.cron}"`);
            return;
        }
        if (!env.CRON_SECRET) {
            throw new Error('[cron] CRON_SECRET is not set');
        }
        const results = await Promise.allSettled(paths.map((path) => runCronRoute(path, env, ctx)));
        const failures = results.filter((r): r is PromiseRejectedResult => r.status === 'rejected');
        if (failures.length > 0) {
            // Throwing marks the invocation as failed in the Cloudflare dashboard.
            throw new AggregateError(failures.map((f) => f.reason), '[cron] One or more cron routes failed');
        }
    },
};

// Durable Objects used by OpenNext must be re-exported from the entry point.
// @ts-ignore see above
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js';
