// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // `prisma generate` (npm postinstall) doesn't need a database, so CI
    // installs without DATABASE_URL must not fail here. Migrate commands
    // still error out against an empty URL.
    url: process.env.DATABASE_URL ?? "",
  },
});
