import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import * as Localization from 'expo-localization';

// Import translation files
// Note: These will be generated by the translation script
import de from '../translations/de.json';
import en from '../translations/en.json';
import tr from '../translations/tr.json';
import it from '../translations/it.json';
import fr from '../translations/fr.json';

const resources = {
  de: { translation: de },
  en: { translation: en },
  tr: { translation: tr },
  it: { translation: it },
  fr: { translation: fr },
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: Localization.getLocales()[0].languageCode ?? 'de',
    fallbackLng: 'de',
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
